//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEV.Crm.Plugins.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SEV.Crm.Plugins.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessConfiguratorAbsractFactory: Failed to retrieve BusinessConfiguratorFactory for the {0} entity..
        /// </summary>
        internal static string BusinessConfiguratorAbsractFactoryError {
            get {
                return ResourceManager.GetString("BusinessConfiguratorAbsractFactoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Failed to retrieve BusinessConfigurator for the {1} event..
        /// </summary>
        internal static string BusinessConfiguratorFactoryError {
            get {
                return ResourceManager.GetString("BusinessConfiguratorFactoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrmServiceProvider: Failed to retrieve the {0} service..
        /// </summary>
        internal static string CrmServiceProviderError {
            get {
                return ResourceManager.GetString("CrmServiceProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrmPluginStageExtractor : can not extract CrmPluginEvent element from the string &apos;{0}&apos;..
        /// </summary>
        internal static string PluginEventExtractorError {
            get {
                return ResourceManager.GetString("PluginEventExtractorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PluginExecutorFactory: Failed to retrieve PluginExecutor for the {0} entity..
        /// </summary>
        internal static string PluginExecutorFactoryError {
            get {
                return ResourceManager.GetString("PluginExecutorFactoryError", resourceCulture);
            }
        }
    }
}
